### PR TITLE
[JENKINS-33230] Disable WARNING log when folder is already existed

### PR DESCRIPTION
**Pull request by totoroliu**
https://issues.jenkins-ci.org/browse/JENKINS-33230

### CODE REVIEW

**Comment by olivergondza** [comment]
:+1:

**Comment by pfalcon** [comment]
@kohsuke , @KostyaSha : Any chance to have this merged/new plugin version released? As https://issues.jenkins-ci.org/browse/JENKINS-33230 describes, this leads to visible Jenkins slowdown and high disk space usage, which can easily lead to disk overflow which in turn may lead to jenkins losing parts of its configuration due to not being able to save it to disk. Thanks!

**Comment by KostyaSha** [comment]
I'm not a maintainer, probably try ping latest committers.

**Comment by pfalcon** [comment]
Thanks for merging!

**Pull request merged**
