### PR TITLE
[FIXED JENKINS-24020] Fail-fast Matrix builds, as soon some configuration fail

### PR DESCRIPTION
**Pull request by bkmeneguello**

### CODE REVIEW

**Comment by bkmeneguello** [comment]
There are any pending issues/validations for this?

**Comment by bkmeneguello** [comment]
bump!?

**Comment by bkmeneguello** [comment]
@oleg-nenashev @olivergondza @jglick @kohsuke
PR still pending. Can it be merged?

**Comment by olivergondza** [comment]
@bkmeneguello, can you resolve the conflict?

**Comment by bkmeneguello** [comment]
@olivergondza resolved

**Comment by bkmeneguello** [comment]
Bump? @oleg-nenashev @olivergondza @jglick @kohsuke?

**Comment by bkmeneguello** [comment]
No one else?

**Comment by oleg-nenashev** [comment]
Sorry,  managed to miss all notifications

**Comment by oleg-nenashev** [comment]
It is hard to review the pull request, but it looks good to me.
Since there is no new options, I suppose it slightly alters the default behavior, but does not interrupt the matrix build immediately after the failure. Is is correct, @bkmeneguello?

**Comment by bkmeneguello** [comment]
@oleg-nenashev Actually it changes the build result as soon as possible when the configuration fails and dumps to the log the updates when they occur.
I've changed the behaviour from blocking to non-blocking. But everything else keeps the same.

**Pull request closed without merging**
