### PR TITLE
[JENKINS-66450] Utilize new build status

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed utilizes the new build status, like it's used it other parts of Jenkins.

turns into

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did

### CODE REVIEW

**Comment by gjabouley-invn** [comment]
Hi, this is a great change, would love to see it quickly shipped 👍

**Comment by NotMyFault** [comment]
Thanks for linking the issue, I wasn't aware of it being an actually feature request 👍🏻

**Comment by NotMyFault** [comment]
Mind taking a look @jglick ?

**Comment by jglick** [comment]
No clue who maintains this. I generally steer clear of this plugin and others that are arguably superseded by Pipeline.

**Review by jglick — APPROVED** [review]
Tested in baseline version as well as 2.332 and it seems to work as advertised. Thanks!

**Pull request merged**
