### PR TITLE
[FIXED JENKINS-28909] Do not enforce 'good' chars for axis values

### PR DESCRIPTION
**Pull request by olivergondza**
[JENKINS-28909](https://issues.jenkins-ci.org/browse/JENKINS-28909)

### CODE REVIEW

**Comment by daniel-beck** [comment]
So only `,` is disallowed for values, `=` and `/` are in?

**Comment by olivergondza** [comment]
Yes, they seem to be handled correctly.

**Comment by daniel-beck** [comment]
:+1:

**Comment by olivergondza** [comment]
I will release this fix tomorrow, unless there are objections. The issue seems quite severe to me. I am surprised thee is not more people reporting this.

**Comment by daniel-beck** [comment]
We've lived with too permissive axes forever, so even if this overshoots, it cannot be worse than what we always had. So I completely agree.

**Comment by jglick** [comment]
I hope there is some kind of compensatory encoding to escape weird values in both URLs and project disk locations? Otherwise we could have accidental or malicious problems with `/`, `..`, etc.

**Comment by jglick** [comment]
This I suppose amends #14?

**Comment by olivergondza** [comment]
Amends _and_ fixes the issue it introduced!

**Pull request merged**
