### PR TITLE
Improved odd translation

### PR DESCRIPTION
**Pull request by phoenix384**
PS: I don't know why the other two lines are marked as changed

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
LGTM, but I'm not a native speaker.

@daniel-beck @albers 
Could you verify it?

**Comment by daniel-beck** [comment]
@phoenix384 You changed the encoding from CP 1252, Latin 1 or similar to UTF-8. Hence the changes in the 'unmodified' lines, the umlauts got different bytes.

**Comment by daniel-beck** [comment]
Looks definitively like an improvement. Both terms are correct German, but *Einstellungen* means *Settings*, which is one of the possible meanings of *Configuration*, but it just doesn't apply in this context (the noun for `MatrixConfiguration`).

Still, I don't use Jenkins in German, and don't know whether this change is consistent with the rest.

**Comment by albers** [comment]
Localization LGTM, thanks.

@phoenix384 Please save the file with Latin-1 or ISO-8859-1 encoding as @daniel-beck suggested. Property files should not be utf-8 encoded.

**Comment by albers** [comment]
ping @phoenix384

**Comment by phoenix384** [comment]
I just edited it via the Github online editor. I don't know why it changed the encoding or how to prevent it from doing so.

**Comment by phoenix384** [comment]
Sorry, but I only managed to correct this by creating a new PR: https://github.com/jenkinsci/matrix-project-plugin/pull/38

**Pull request closed without merging**
